// import { Video } from '@/types';

// export const SAMPLE_VIDEOS: Video[] = [
//   {
//     id: 'tech-1',
//     title: 'Introduction to React 19 - New Features and Updates',
//     thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
//     duration: 725, // 12:05
//     category: 'Technology',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
//     description: 'Explore the latest features in React 19',
//     views: 125000,
//   },
//   {
//     id: 'tech-2',
//     title: 'TypeScript Best Practices for Large Scale Applications',
//     thumbnail: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80',
//     duration: 892, // 14:52
//     category: 'Technology',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
//     description: 'Learn advanced TypeScript patterns',
//     views: 89000,
//   },
//   {
//     id: 'tech-3',
//     title: 'Building Modern Web Apps with Vite and React',
//     thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
//     duration: 645, // 10:45
//     category: 'Technology',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
//     description: 'Fast development with Vite',
//     views: 67000,
//   },
  
//   {
//     id: 'gaming-1',
//     title: 'Epic Gaming Moments - Top 10 Plays of the Week',
//     thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80',
//     duration: 480, // 8:00
//     category: 'Gaming',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
//     description: 'Amazing gaming highlights',
//     views: 234000,
//   },
//   {
//     id: 'gaming-2',
//     title: 'Pro Gaming Tips: Improve Your Skills Fast',
//     thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80',
//     duration: 567, // 9:27
//     category: 'Gaming',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
//     description: 'Master your favorite games',
//     views: 156000,
//   },
//   {
//     id: 'gaming-3',
//     title: 'The Future of Gaming - VR and AR Revolution',
//     thumbnail: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&q=80',
//     duration: 720, // 12:00
//     category: 'Gaming',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
//     description: 'Exploring next-gen gaming',
//     views: 198000,
//   },
  
//   {
//     id: 'music-1',
//     title: 'Acoustic Guitar Tutorial for Beginners',
//     thumbnail: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80',
//     duration: 425, // 7:05
//     category: 'Music',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
//     description: 'Learn guitar basics',
//     views: 45000,
//   },
//   {
//     id: 'music-2',
//     title: 'Top 10 Music Production Tips from the Pros',
//     thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&q=80',
//     duration: 683, // 11:23
//     category: 'Music',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
//     description: 'Professional music production',
//     views: 78000,
//   },
//   {
//     id: 'music-3',
//     title: 'The Science of Sound: Understanding Audio Engineering',
//     thumbnail: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&q=80',
//     duration: 540, // 9:00
//     category: 'Music',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
//     description: 'Deep dive into audio',
//     views: 92000,
//   },
  
//   {
//     id: 'sports-1',
//     title: 'Incredible Sports Highlights - Best Moments 2024',
//     thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
//     duration: 380, // 6:20
//     category: 'Sports',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
//     description: 'Top sports moments',
//     views: 456000,
//   },
//   {
//     id: 'sports-2',
//     title: 'Fitness Training Guide - Full Body Workout',
//     thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
//     duration: 925, // 15:25
//     category: 'Sports',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
//     description: 'Complete workout routine',
//     views: 234000,
//   },
//   {
//     id: 'sports-3',
//     title: 'Soccer Skills Masterclass with Pro Players',
//     thumbnail: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&q=80',
//     duration: 615, // 10:15
//     category: 'Sports',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
//     description: 'Learn from the pros',
//     views: 312000,
//   },
  
//   {
//     id: 'edu-1',
//     title: 'Understanding Quantum Physics - Made Simple',
//     thumbnail: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?w=800&q=80',
//     duration: 847, // 14:07
//     category: 'Education',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
//     description: 'Quantum physics explained',
//     views: 178000,
//   },
//   {
//     id: 'edu-2',
//     title: 'World History: The Industrial Revolution',
//     thumbnail: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&q=80',
//     duration: 720, // 12:00
//     category: 'Education',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
//     description: 'Historical deep dive',
//     views: 134000,
//   },
//   {
//     id: 'edu-3',
//     title: 'Mathematics for Everyone - Calculus Basics',
//     thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&q=80',
//     duration: 965, // 16:05
//     category: 'Education',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
//     description: 'Learn calculus fundamentals',
//     views: 89000,
//   },
  
//   {
//     id: 'ent-1',
//     title: 'Comedy Gold - Funniest Moments Compilation',
//     thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80',
//     duration: 445, // 7:25
//     category: 'Entertainment',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
//     description: 'Non-stop laughter',
//     views: 567000,
//   },
//   {
//     id: 'ent-2',
//     title: 'Behind the Scenes: Movie Magic Revealed',
//     thumbnail: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80',
//     duration: 785, // 13:05
//     category: 'Entertainment',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
//     description: 'Movie production secrets',
//     views: 298000,
//   },
//   {
//     id: 'ent-3',
//     title: 'Travel Vlog: Exploring Hidden Gems Around the World',
//     thumbnail: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80',
//     duration: 1020, // 17:00
//     category: 'Entertainment',
//     url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
//     description: 'Adventure awaits',
//     views: 423000,
//   },
// ];

// export const CATEGORIES = [
//   'Technology',
//   'Gaming',
//   'Music',
//   'Sports',
//   'Education',
//   'Entertainment',
// ] as const;

import { Video } from '@/types';

// Using the provided dataset with MP4 video sources for playback
// Note: YouTube URLs don't work with HTML5 video player, using sample MP4s instead
export const SAMPLE_VIDEOS: Video[] = [
  // Social Media AI Category
  {
    id: '_HL7l_62bUc',
    title: 'AI Motivational Reel Banao Free Mein',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b29/TC9Jbr_MBNoEJm5Mwhc2F.png',
    duration: 420,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    description: 'Learn how to create AI-powered motivational reels for free',
  },
  {
    id: 'avZd1bSvqyE',
    title: 'Social Media Ke Liye Facts Video Banao',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b28/7hy7WSculPFwQtcVu0BzN.png',
    duration: 380,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    description: 'Create engaging facts videos for social media using AI',
  },
  {
    id: 'meVTqNn1P5A',
    title: 'Instagram Ka Naya AI Feature',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2a/T6DpgH_xrEN15r1f3rquu-.png',
    duration: 340,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    description: 'Discover Instagram\'s new AI features',
  },
  {
    id: 'x3LsfGSP-Hk',
    title: 'Ab Meta AI Karega Aapki Photo Edit',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b29/Joql9g8WnlzhXj5sDCfN5.png',
    duration: 450,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    description: 'Meta AI will now edit your photos automatically',
  },
  {
    id: 'lfDxSj9xnmI',
    title: 'AI Se Reel Banaye 1 Minute Mein',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b29/F5qaMZqTNvp4Z9KmprqEV.png',
    duration: 280,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    description: 'Create reels in just 1 minute using AI',
  },
  {
    id: 'LX598gRezv4',
    title: 'Instagram AI Character Kaise Banaye',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b28/r_1g2P1AnedS4SSN89vwG.png',
    duration: 520,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    description: 'How to create AI characters for Instagram',
  },
  {
    id: 'BDN_N-mAbkU',
    title: 'Trending 3D AI Photo Kaise Banaye',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b28/rKMuPZJCl1S9wIpP-knMt.png',
    duration: 390,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    description: 'Create trending 3D AI photos easily',
  },
  {
    id: 'ogAG6GcmHjQ',
    title: 'Social Media Content Ke Liye Best AI Tools',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b29/M-Gw4R2hoRC29el9zQ-uI.png',
    duration: 580,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    description: 'Best AI tools for social media content creation',
  },
  {
    id: 'mobK-kGDxWo',
    title: 'AI Tools Se Asani Se Content Creator Bano',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b29/9kGHRX9Gj9OcEJwBuVDt1.png',
    duration: 460,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    description: 'Become a content creator easily with AI tools',
  },
  {
    id: '6ZqxfloJ3Vk',
    title: 'AI Ki Madad Se Faceless Videos Banao',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b28/y9MpZDuI2z1kZV_mNA2Qd.png',
    duration: 410,
    category: 'Social Media AI',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    description: 'Create faceless videos with AI assistance',
  },

  // AI Income Category
  {
    id: 'TpW3QxwADgE',
    title: 'Yeh Free AI Tool Se Paise Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2e/SK5TdlG5x5Tc-KG29U_Jm.png',
    duration: 480,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    description: 'Earn money using this free AI tool',
  },
  {
    id: 'Wi9cKN6Fg1E',
    title: 'AI Clone Se Paise Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a883ea8/MuPkcktStazw3ImTOJGIm.png',
    duration: 540,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    description: 'Make money with AI clones',
  },
  {
    id: 'mkGhOo_oB4o',
    title: 'Pictory AI Se Youtube Side Income Bann Sakta Hai?',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2f/uOV2zrTv8yrsXW3v5nKX2.png',
    duration: 620,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    description: 'Can you create YouTube side income with Pictory AI?',
  },
  {
    id: 'k-aVj_Geyvc',
    title: 'DesiVocal Se Bharpur Paise Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2e/MBiZLEvaN7FdmVqUDZcJR.png',
    duration: 390,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    description: 'Earn substantial money with DesiVocal',
  },
  {
    id: 'gUDRMsW3v1U',
    title: 'AI Se WordPress Plugin Banakar Paise Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2f/RWn-4G0cCcDogRcsUuZHY.png',
    duration: 560,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    description: 'Create WordPress plugins with AI and earn money',
  },
  {
    id: 'I93GvazYTuc',
    title: 'Quick Money AI Se Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2e/owJQOWUFlWuxa7HZuageT.png',
    duration: 320,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    description: 'Earn quick money with AI',
  },
  {
    id: 'ibI3RRJN0Wg',
    title: 'AI Hindi Story Se Youtube Pe Paise Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a883f60/F8LDntc6q7xMdyJfjC17W.png',
    duration: 490,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    description: 'Earn money on YouTube with AI Hindi stories',
  },
  {
    id: 'TPtAAW3LSP4',
    title: 'Kya Hum AI Se Active Income Bana Sakta Hai?',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2e/B7yW2SjAclyMReSqcYSfM.png',
    duration: 580,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    description: 'Can we create active income with AI?',
  },
  {
    id: 'JrbFF30SHzc',
    title: 'Fiverr Par AI Se Paise Kamao',
    thumbnail: 'https://v3b.fal.media/files/b/0a883ea7/LOY5sDu5YgN2GaPpJXg5J.png',
    duration: 440,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    description: 'Earn money on Fiverr using AI',
  },
  {
    id: 'VKpgO2FVXa0',
    title: 'AI Tool Se Side Business Shuru Karo!',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b2e/GuuKXPXsea-n1IM1VW6jt.png',
    duration: 510,
    category: 'AI Income',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    description: 'Start a side business with AI tools',
  },

  // AI Essentials Category
  {
    id: 'DzCWyUCr9LQ',
    title: '50 Lakh Ki AI Course Bilkul Free!',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b39/BhkweJb1D0L7oiuL4XdSo.png',
    duration: 380,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    description: 'AI course worth 50 lakhs, absolutely free!',
  },
  {
    id: 'kmHt5BHXYvU',
    title: 'Google Ka AI Course 100% Free',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b3a/3rE_mrJr2af5XMJxEXuV_.png',
    duration: 520,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    description: 'Google\'s AI course completely free',
  },
  {
    id: '_w07HdQxuIw',
    title: 'Nvidia Ka Free Generative AI Course',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b3a/oD30ARDLlEDQxinlqQvwZ.png',
    duration: 610,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    description: 'Nvidia\'s free generative AI course',
  },
  {
    id: 'ua-NkDcLneo',
    title: 'Data Annotation Projects WFH Ke Liye',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b3a/36455BIBrDfyDFwJBbyzh.png',
    duration: 450,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    description: 'Work from home data annotation projects',
  },
  {
    id: 'sAz94JQ6v4w',
    title: '5 Best Free AI Skills Courses',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b39/U9h2KU6HwQ1BX45INCy0y.png',
    duration: 490,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    description: 'Top 5 free AI skills courses',
  },
  {
    id: '5kQdqXsmnBc',
    title: 'Indian Government Ka AI Course',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b39/zBWHk56rKEmLqmbWXN9N6.png',
    duration: 540,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    description: 'AI course by Indian Government',
  },
  {
    id: 'IoslCQQ4lcE',
    title: 'Lakhon Kamao Yeh Course Karke',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b39/ZHWjXBXcErWgNiR2fz2na.png',
    duration: 580,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    description: 'Earn lakhs by completing this course',
  },
  {
    id: 'SxtDXU_rM1s',
    title: 'Crowdgen Platform Ka AI Training Jobs',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b3a/O9KNgQYUNIXrTjvwZWEmE.png',
    duration: 420,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    description: 'AI training jobs on Crowdgen platform',
  },
  {
    id: 'gcOFJSc-lWs',
    title: 'EY Aur Microsoft Ka Free AI Course',
    thumbnail: 'https://v3b.fal.media/files/b/0a877b3a/o4DNA97xHC1BixuETJS_J.png',
    duration: 470,
    category: 'AI Essentials',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    description: 'Free AI course by EY and Microsoft',
  },
];

export const CATEGORIES = [
  'Social Media AI',
  'AI Income',
  'AI Essentials',
] as const;