import { Video } from '@/types';

// Using working alternative video URLs that bypass CORS issues
export const SAMPLE_VIDEOS: Video[] = [
  // Social Media AI Category
  {
    id: '_HL7l_62bUc',
    title: 'AI Motivational Reel Banao Free Mein',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
    duration: 420,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Learn how to create AI-powered motivational reels for free',
  },
  {
    id: 'avZd1bSvqyE',
    title: 'Social Media Ke Liye Facts Video Banao',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
    duration: 380,
    category: 'Social Media AI',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Create engaging facts videos for social media using AI',
  },
  {
    id: 'meVTqNn1P5A',
    title: 'Instagram Ka Naya AI Feature',
    thumbnail: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&q=80',
    duration: 340,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Discover Instagram\'s new AI features',
  },
  {
    id: 'x3LsfGSP-Hk',
    title: 'Ab Meta AI Karega Aapki Photo Edit',
    thumbnail: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&q=80',
    duration: 450,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Meta AI will now edit your photos automatically',
  },
  {
    id: 'lfDxSj9xnmI',
    title: 'AI Se Reel Banaye 1 Minute Mein',
    thumbnail: 'https://images.unsplash.com/photo-1665686304355-0b09b1e3b03c?w=800&q=80',
    duration: 280,
    category: 'Social Media AI',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Create reels in just 1 minute using AI',
  },
  {
    id: 'LX598gRezv4',
    title: 'Instagram AI Character Kaise Banaye',
    thumbnail: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80',
    duration: 520,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'How to create AI characters for Instagram',
  },
  {
    id: 'BDN_N-mAbkU',
    title: 'Trending 3D AI Photo Kaise Banaye',
    thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80',
    duration: 390,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Create trending 3D AI photos easily',
  },
  {
    id: 'ogAG6GcmHjQ',
    title: 'Social Media Content Ke Liye Best AI Tools',
    thumbnail: 'https://images.unsplash.com/photo-1679403323246-1f0d50e83a01?w=800&q=80',
    duration: 580,
    category: 'Social Media AI',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Best AI tools for social media content creation',
  },
  {
    id: 'mobK-kGDxWo',
    title: 'AI Tools Se Asani Se Content Creator Bano',
    thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80',
    duration: 460,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Become a content creator easily with AI tools',
  },
  {
    id: '6ZqxfloJ3Vk',
    title: 'AI Ki Madad Se Faceless Videos Banao',
    thumbnail: 'https://images.unsplash.com/photo-1676573409146-a31c633f3660?w=800&q=80',
    duration: 410,
    category: 'Social Media AI',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Create faceless videos with AI assistance',
  },

  // AI Income Category
  {
    id: 'TpW3QxwADgE',
    title: 'Yeh Free AI Tool Se Paise Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1633158829875-e5316a358c6f?w=800&q=80',
    duration: 480,
    category: 'AI Income',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Earn money using this free AI tool',
  },
  {
    id: 'Wi9cKN6Fg1E',
    title: 'AI Clone Se Paise Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1640340434855-6084b1f4901c?w=800&q=80',
    duration: 540,
    category: 'AI Income',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Make money with AI clones',
  },
  {
    id: 'mkGhOo_oB4o',
    title: 'Pictory AI Se Youtube Side Income Bann Sakta Hai?',
    thumbnail: 'https://images.unsplash.com/photo-1579532537902-1e50099867b4?w=800&q=80',
    duration: 620,
    category: 'AI Income',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Can you create YouTube side income with Pictory AI?',
  },
  {
    id: 'k-aVj_Geyvc',
    title: 'DesiVocal Se Bharpur Paise Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80',
    duration: 390,
    category: 'AI Income',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Earn substantial money with DesiVocal',
  },
  {
    id: 'gUDRMsW3v1U',
    title: 'AI Se WordPress Plugin Banakar Paise Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&q=80',
    duration: 560,
    category: 'AI Income',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Create WordPress plugins with AI and earn money',
  },
  {
    id: 'I93GvazYTuc',
    title: 'Quick Money AI Se Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1634704784915-aacf363b021f?w=800&q=80',
    duration: 320,
    category: 'AI Income',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Earn quick money with AI',
  },
  {
    id: 'ibI3RRJN0Wg',
    title: 'AI Hindi Story Se Youtube Pe Paise Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=800&q=80',
    duration: 490,
    category: 'AI Income',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Earn money on YouTube with AI Hindi stories',
  },
  {
    id: 'TPtAAW3LSP4',
    title: 'Kya Hum AI Se Active Income Bana Sakta Hai?',
    thumbnail: 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=800&q=80',
    duration: 580,
    category: 'AI Income',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Can we create active income with AI?',
  },
  {
    id: 'JrbFF30SHzc',
    title: 'Fiverr Par AI Se Paise Kamao',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80',
    duration: 440,
    category: 'AI Income',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Earn money on Fiverr using AI',
  },
  {
    id: 'VKpgO2FVXa0',
    title: 'AI Tool Se Side Business Shuru Karo!',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    duration: 510,
    category: 'AI Income',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Start a side business with AI tools',
  },

  // AI Essentials Category
  {
    id: 'DzCWyUCr9LQ',
    title: '50 Lakh Ki AI Course Bilkul Free!',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80',
    duration: 380,
    category: 'AI Essentials',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'AI course worth 50 lakhs, absolutely free!',
  },
  {
    id: 'kmHt5BHXYvU',
    title: 'Google Ka AI Course 100% Free',
    thumbnail: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=800&q=80',
    duration: 520,
    category: 'AI Essentials',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Google\'s AI course completely free',
  },
  {
    id: '_w07HdQxuIw',
    title: 'Nvidia Ka Free Generative AI Course',
    thumbnail: 'https://images.unsplash.com/photo-1555255707-c07966088b7b?w=800&q=80',
    duration: 610,
    category: 'AI Essentials',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Nvidia\'s free generative AI course',
  },
  {
    id: 'ua-NkDcLneo',
    title: 'Data Annotation Projects WFH Ke Liye',
    thumbnail: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80',
    duration: 450,
    category: 'AI Essentials',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Work from home data annotation projects',
  },
  {
    id: 'sAz94JQ6v4w',
    title: '5 Best Free AI Skills Courses',
    thumbnail: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&q=80',
    duration: 490,
    category: 'AI Essentials',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'Top 5 free AI skills courses',
  },
  {
    id: '5kQdqXsmnBc',
    title: 'Indian Government Ka AI Course',
    thumbnail: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80',
    duration: 540,
    category: 'AI Essentials',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'AI course by Indian Government',
  },
  {
    id: 'IoslCQQ4lcE',
    title: 'Lakhon Kamao Yeh Course Karke',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80',
    duration: 580,
    category: 'AI Essentials',
    url: 'https://www.w3schools.com/html/movie.mp4',
    description: 'Earn lakhs by completing this course',
  },
  {
    id: 'SxtDXU_rM1s',
    title: 'Crowdgen Platform Ka AI Training Jobs',
    thumbnail: 'https://images.unsplash.com/photo-1552581234-26160f608093?w=800&q=80',
    duration: 420,
    category: 'AI Essentials',
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    description: 'AI training jobs on Crowdgen platform',
  },
  {
    id: 'gcOFJSc-lWs',
    title: 'EY Aur Microsoft Ka Free AI Course',
    thumbnail: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&q=80',
    duration: 470,
    category: 'AI Essentials',
    url: 'https://media.w3.org/2010/05/sintel/trailer_hd.mp4',
    description: 'Free AI course by EY and Microsoft',
  },
];

export const CATEGORIES = [
  'Social Media AI',
  'AI Income',
  'AI Essentials',
] as const;